name: Makefile CI

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:
    runs-on: ubuntu-latest
    container: m3hh/latex:latest
    

    steps:
    - name: Check out the repo
      uses: actions/checkout@v2

    - name: Install other dependencies
      run: apt-get update && apt-get install -y ttf-mscorefonts-installer make python3 python3-venv

    - name: Install dependencies
      run: make
