name: Makefile CI

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:

    runs-on: ubuntu-latest
    container: blang/latex:ctanfull

    steps:
    - uses: actions/checkout@v2
      run: tlmgr install mathfont
    - name: Install using tlmgr
        
    - name: Install dependencies
      run: make
